# -*-coding: utf-8 -*-

EMOTICON_LIST = [
    {'text': '[微笑]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/微笑.jpg'},
    {'text': '[撇嘴]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/撇嘴.jpg'},
    {'text': '[色]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/色.jpg'},
    {'text': '[发呆]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/发呆.jpg'},
    {'text': '[得意]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/得意.jpg'},
    {'text': '[流泪]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/流泪.jpg'},
    {'text': '[害羞]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/害羞.jpg'},
    {'text': '[闭嘴]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/闭嘴.jpg'},
    # {'text': '[睡]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/睡.jpg'},
    {'text': '[大哭]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/大哭.jpg'},
    {'text': '[尴尬]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/尴尬.jpg'},
    {'text': '[发怒]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/发怒.jpg'},
    # {'text': '[调皮]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/调皮.jpg'},
    {'text': '[呲牙]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/呲牙.jpg'},
    # {'text': '[惊讶]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/惊讶.jpg'},
    # {'text': '[难过]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/难过.jpg'},
    # {'text': '[囧]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/囧.jpg'},
    # {'text': '[抓狂]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/抓狂.jpg'},
    {'text': '[吐]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/吐.jpg'},
    {'text': '[偷笑]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/偷笑.jpg'},
    {'text': '[愉快]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/愉快.jpg'},
    # {'text': '[白眼]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/白眼.jpg'},
    # {'text': '[傲慢]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/傲慢.jpg'},
    {'text': '[困]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/困.jpg'},
    # {'text': '[惊恐]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/惊恐.jpg'},
    {'text': '[憨笑]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/憨笑.jpg'},
    {'text': '[悠闲]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/悠闲.jpg'},
    {'text': '[咒骂]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/咒骂.jpg'},
    {'text': '[疑问]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/疑问.jpg'},
    # {'text': '[嘘]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/嘘.jpg'},
    {'text': '[晕]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/晕.jpg'},
    # {'text': '[衰]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/衰.jpg'},
    # {'text': '[骷髅]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/骷髅.jpg'},
    {'text': '[敲打]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/敲打.jpg'},
    {'text': '[再见]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/再见.jpg'},
    {'text': '[擦汗]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/擦汗.jpg'},
    {'text': '[抠鼻]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/抠鼻.jpg'},
    # {'text': '[鼓掌]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/鼓掌.jpg'},
    {'text': '[坏笑]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/坏笑.jpg'},
    # {'text': '[右哼哼]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/右哼哼.jpg'},
    # {'text': '[鄙视]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/鄙视.jpg'},
    # {'text': '[委屈]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/委屈.jpg'},
    {'text': '[快哭]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/快哭.jpg'},
    # {'text': '[阴险]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/阴险.jpg'},
    # {'text': '[亲亲]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/亲亲.jpg'},
    # {'text': '[可怜]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/可怜.jpg'},
    {'text': '[嘿哈]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/嘿哈.jpg'},
    {'text': '[捂脸]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/捂脸.jpg'},
    {'text': '[奸笑]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/奸笑.jpg'},
    {'text': '[机智]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/机智.jpg'},
    {'text': '[皱眉]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/皱眉.jpg'},
    {'text': '[耶]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/耶.jpg'},
    {'text': '[吃瓜]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/吃瓜.jpg'},
    {'text': '[加油]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/加油.jpg'},
    {'text': '[汗]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/汗.jpg'},
    {'text': '[天啊]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/天啊.jpg'},
    {'text': '[Emm]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/Emm.jpg'},
    {'text': '[社会社会]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/社会社会.jpg'},
    {'text': '[旺柴]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/旺柴.jpg'},
    {'text': '[好的]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/好的.jpg'},
    {'text': '[打脸]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/打脸.jpg'},
    {'text': '[加油加油]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/加油加油.jpg'},
    {'text': '[哇]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/哇.jpg'},
    {'text': '[翻白眼]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/翻白眼.jpg'},
    {'text': '[666]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/666.jpg'},
    {'text': '[让我看看]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/让我看看.jpg'},
    {'text': '[叹气]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/叹气.jpg'},
    {'text': '[苦涩]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/苦涩.jpg'},
    {'text': '[裂开]', 'url': 'https://raw.githubusercontent.com/koonchung/WechatEmoticonBot/master/wechatemoticonbot/images/裂开.jpg'}
]
